// Regenerates src/payload-types.ts from src/payload.config.ts.
//
// This bypasses the `payload generate:types` CLI, which silently produces no
// output/file in this project (tsx's worker-based ESM loader used by the CLI's
// bin wrapper appears to tear down before the write completes here). Calling
// the same Payload internals directly, driven by plain `tsx`, works reliably.
import { pathToFileURL } from 'node:url'
import path from 'node:path'
import fs from 'node:fs/promises'

const configPath = path.resolve('src/payload.config.ts')
const mod = await import(pathToFileURL(configPath).toString())
const config = await mod.default

const { configToJSONSchema } = await import('payload')
const { initI18n } = await import('@payloadcms/translations')
const { compile } = await import('json-schema-to-typescript')

const languages = Object.keys(config.i18n.supportedLanguages)
const language = languages.includes('en') ? 'en' : config.i18n.fallbackLanguage
const i18n = await initI18n({ config: config.i18n, context: 'api', language })

const jsonSchema = configToJSONSchema(config, config.db.defaultIDType, i18n)

const compiled = await compile(jsonSchema, 'Config', {
  bannerComment:
    '/* tslint:disable */\n/* eslint-disable */\n/**\n* This file was automatically generated by Payload.\n* DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,\n* and re-run `npm run generate:types`.\n*/',
  style: { singleQuote: true },
  unreachableDefinitions: true,
  cwd: process.cwd(),
})

const declare = `declare module 'payload' {\n  export interface GeneratedTypes extends Config {}\n}`

await fs.writeFile(config.typescript.outputFile, `${compiled}\n\n${declare}`)
console.log(`Types written to ${config.typescript.outputFile}`)
