/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `npm run generate:types`.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    orders: Order;
    'wedding-inquiries': WeddingInquiry;
    'custom-bouquet-requests': CustomBouquetRequest;
    'business-inquiries': BusinessInquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect;
    media: MediaSelect;
    categories: CategoriesSelect;
    products: ProductsSelect;
    orders: OrdersSelect;
    'wedding-inquiries': WeddingInquiriesSelect;
    'custom-bouquet-requests': CustomBouquetRequestsSelect;
    'business-inquiries': BusinessInquiriesSelect;
    'payload-kv': PayloadKvSelect;
    'payload-locked-documents': PayloadLockedDocumentsSelect;
    'payload-preferences': PayloadPreferencesSelect;
    'payload-migrations': PayloadMigrationsSelect;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    'site-settings': SiteSetting;
    'subscription-info': SubscriptionInfo;
    'wedding-page': WeddingPage;
    'formats-section': FormatsSection;
    'instagram-integration': InstagramIntegration;
    'feature-strip': FeatureStrip;
    'how-it-works-section': HowItWorksSection;
    'subscription-pricing': SubscriptionPricing;
    testimonials: Testimonial;
    'faq-section': FaqSection;
  };
  globalsSelect: {
    hero: HeroSelect;
    'site-settings': SiteSettingsSelect;
    'subscription-info': SubscriptionInfoSelect;
    'wedding-page': WeddingPageSelect;
    'formats-section': FormatsSectionSelect;
    'instagram-integration': InstagramIntegrationSelect;
    'feature-strip': FeatureStripSelect;
    'how-it-works-section': HowItWorksSectionSelect;
    'subscription-pricing': SubscriptionPricingSelect;
    testimonials: TestimonialsSelect;
    'faq-section': FaqSectionSelect;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'owner' | 'florist';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  /**
   * FAQ-блок під сіткою товарів на сторінці цієї категорії
   */
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Заголовок H1 на сторінці товару, якщо має відрізнятись від назви в кошику/картках (необовʼязково)
   */
  pdpHeading?: string | null;
  /**
   * Короткий підпис під назвою на картці товару, напр. "Компактний затишний букет" (необовʼязково)
   */
  cardSubtitle?: string | null;
  slug: string;
  /**
   * Той самий товар може належати кільком категоріям (напр. підписка одночасно й "Підписка на квіти", й "Весільна підписка")
   */
  categories: (number | Category)[];
  /**
   * Базова ціна в копійках (щоб уникнути похибок округлення), напр. 45000 = 450.00 грн
   */
  price: number;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Напр. розмір букета або частота підписки
   */
  variants?:
    | {
        label: string;
        /**
         * Копійки, може бути відʼємним
         */
        priceModifier?: number | null;
        /**
         * Якщо вказано, замінює фото товару при виборі цього варіанту
         */
        image?: (number | null) | Media;
        sku?: string | null;
        /**
         * Позначає варіант як обраний за замовчуванням, з бейджем "Рекомендовано" на сторінці товару
         */
        recommended?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Частота доставок для вибору на сторінці товару (напр. Щотижня / Раз на 2 тижні / Щомісяця). Порожньо — блок не показується.
   */
  deliveryFrequencies?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Дні доставки для вибору на сторінці товару (напр. Вівторок / П'ятниця). Порожньо — блок не показується.
   */
  deliveryDays?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Блок довіри під кнопкою купівлі на сторінці товару (необовʼязково)
   */
  trustBadges?:
    | {
        /**
         * Емодзі, напр. 🎁
         */
        icon?: string | null;
        /**
         * Жирний заголовок
         */
        label: string;
        /**
         * Короткий підпис (необовʼязково)
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Напр. "ХІТ ПРОДАЖІВ" — стрічка в кутку картки товару (необовʼязково)
   */
  badge?: string | null;
  /**
   * Показує бейдж "Безкоштовна доставка" на картці товару
   */
  freeDeliveryBadge?: boolean | null;
  /**
   * Показує бейдж "Ваза у подарунок" на картці товару
   */
  vaseGiftBadge?: boolean | null;
  /**
   * Список переваг з ✓ на картці товару (необовʼязково)
   */
  bullets?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Дрібний текст біля ціни, напр. "1 700 грн / букет" (необовʼязково)
   */
  priceSuffixLabel?: string | null;
  /**
   * Текст кнопки на картці товару, напр. "Обрати M" (за замовчуванням "У кошик")
   */
  ctaLabel?: string | null;
  /**
   * Виділяє картку та затемнює кнопку (для рекомендованого плану)
   */
  highlighted?: boolean | null;
  /**
   * Для фільтрів-табів на сторінці категорії (необовʼязково)
   */
  audienceTags?: ('home' | 'business' | 'trial')[] | null;
  /**
   * Для фільтрів-табів на сторінці категорії "Букети" (необовʼязково)
   */
  occasionTags?: ('birthday' | 'romantic' | 'gentle')[] | null;
  /**
   * Показувати в блоці "Додати до замовлення" в кошику
   */
  crossSell?: boolean | null;
  inStock?: boolean | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  customerName: string;
  phone: string;
  email?: string | null;
  /**
   * Замовлення на подарунок іншому отримувачу
   */
  isGift?: boolean | null;
  recipientName?: string | null;
  recipientPhone?: string | null;
  /**
   * Не розкривати деталі замовлення отримувачу (сюрприз)
   */
  giftSurprise?: boolean | null;
  deliveryMethod: 'courier' | 'nova_poshta' | 'pickup';
  /**
   * Кур'єр і Нова пошта
   */
  deliveryCity?: string | null;
  deliveryDate: string;
  /**
   * Кур'єрська доставка
   */
  deliveryAddress?: string | null;
  /**
   * Кур'єрська доставка
   */
  deliveryTimeWindow?:
    ('09:00-12:00' | '10:00-14:00' | '12:00-15:00' | '14:00-18:00' | '15:00-18:00' | '18:00-21:00') | null;
  /**
   * Номер відділення/поштомату
   */
  npOfficeNumber?: string | null;
  /**
   * Ref міста в довіднику Нової пошти
   */
  npCityRef?: string | null;
  /**
   * Ref відділення в довіднику Нової пошти
   */
  npWarehouseRef?: string | null;
  /**
   * Самовивіз — орієнтовний час візиту
   */
  pickupTime?: string | null;
  /**
   * Текст листівки
   */
  cardMessage?: string | null;
  paymentMethod: 'online' | 'installments' | 'business_invoice';
  comment?: string | null;
  items: {
    product: number | Product;
    productName: string;
    variantLabel?: string | null;
    quantity: number;
    /**
     * Копійки
     */
    unitPrice: number;
    /**
     * Копійки
     */
    lineTotal: number;
    id?: string | null;
  }[];
  /**
   * Копійки, рахується автоматично
   */
  orderTotal?: number | null;
  status: 'new' | 'confirmed' | 'in_progress' | 'done' | 'cancelled';
  paymentStatus?: ('not_required' | 'pending' | 'paid' | 'failed' | 'refunded') | null;
  paymentProvider?: ('none' | 'monobank_acquiring' | 'monobank_installments') | null;
  paymentReference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-inquiries".
 */
export interface WeddingInquiry {
  id: number;
  customerName: string;
  phone: string;
  email?: string | null;
  weddingDate?: string | null;
  guestsCount?: number | null;
  /**
   * Орієнтовний бюджет, напр. '20000-30000 грн'
   */
  budget?: string | null;
  comment?: string | null;
  status: 'new' | 'contacted' | 'consultation_scheduled' | 'won' | 'lost';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-bouquet-requests".
 */
export interface CustomBouquetRequest {
  id: number;
  customerName: string;
  phone: string;
  gamma: 'gentle' | 'bright' | 'classic' | 'florist_choice';
  /**
   * Копійки
   */
  budget: number;
  /**
   * Привід (необовʼязково)
   */
  occasion?: string | null;
  /**
   * Улюблені квіти
   */
  likedFlowers?: string | null;
  /**
   * Небажані квіти
   */
  dislikedFlowers?: string | null;
  /**
   * Текст листівки
   */
  cardMessage?: string | null;
  referencePhoto?: (number | null) | Media;
  status: 'new' | 'contacted' | 'in_progress' | 'done' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-inquiries".
 */
export interface BusinessInquiry {
  id: number;
  companyName: string;
  contactPerson: string;
  phone: string;
  businessType: 'restaurant' | 'hotel' | 'beauty' | 'it_office' | 'showroom' | 'other';
  /**
   * Орієнтовний бюджет або кількість локацій, напр. '3 локації, 15000 грн/міс'
   */
  budgetOrLocations?: string | null;
  status: 'new' | 'contacted' | 'trial_week' | 'won' | 'lost';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'wedding-inquiries';
        value: number | WeddingInquiry;
      } | null)
    | ({
        relationTo: 'custom-bouquet-requests';
        value: number | CustomBouquetRequest;
      } | null)
    | ({
        relationTo: 'business-inquiries';
        value: number | BusinessInquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect {
  name?: boolean;
  role?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  email?: boolean;
  resetPasswordToken?: boolean;
  resetPasswordExpiration?: boolean;
  salt?: boolean;
  hash?: boolean;
  loginAttempts?: boolean;
  lockUntil?: boolean;
  sessions?:
    | boolean
    | {
        id?: boolean;
        createdAt?: boolean;
        expiresAt?: boolean;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect {
  alt?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  url?: boolean;
  thumbnailURL?: boolean;
  filename?: boolean;
  mimeType?: boolean;
  filesize?: boolean;
  width?: boolean;
  height?: boolean;
  focalX?: boolean;
  focalY?: boolean;
  sizes?:
    | boolean
    | {
        thumbnail?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
        card?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
        full?:
          | boolean
          | {
              url?: boolean;
              width?: boolean;
              height?: boolean;
              mimeType?: boolean;
              filesize?: boolean;
              filename?: boolean;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect {
  name?: boolean;
  slug?: boolean;
  description?: boolean;
  image?: boolean;
  sortOrder?: boolean;
  faqItems?:
    | boolean
    | {
        question?: boolean;
        answer?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  _status?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect {
  name?: boolean;
  pdpHeading?: boolean;
  cardSubtitle?: boolean;
  slug?: boolean;
  categories?: boolean;
  price?: boolean;
  description?: boolean;
  images?:
    | boolean
    | {
        image?: boolean;
        alt?: boolean;
        id?: boolean;
      };
  variants?:
    | boolean
    | {
        label?: boolean;
        priceModifier?: boolean;
        image?: boolean;
        sku?: boolean;
        recommended?: boolean;
        id?: boolean;
      };
  deliveryFrequencies?:
    | boolean
    | {
        label?: boolean;
        id?: boolean;
      };
  deliveryDays?:
    | boolean
    | {
        label?: boolean;
        id?: boolean;
      };
  trustBadges?:
    | boolean
    | {
        icon?: boolean;
        label?: boolean;
        note?: boolean;
        id?: boolean;
      };
  badge?: boolean;
  freeDeliveryBadge?: boolean;
  vaseGiftBadge?: boolean;
  bullets?:
    | boolean
    | {
        label?: boolean;
        id?: boolean;
      };
  priceSuffixLabel?: boolean;
  ctaLabel?: boolean;
  highlighted?: boolean;
  audienceTags?: boolean;
  occasionTags?: boolean;
  crossSell?: boolean;
  inStock?: boolean;
  featured?: boolean;
  sortOrder?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  _status?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect {
  customerName?: boolean;
  phone?: boolean;
  email?: boolean;
  isGift?: boolean;
  recipientName?: boolean;
  recipientPhone?: boolean;
  giftSurprise?: boolean;
  deliveryMethod?: boolean;
  deliveryCity?: boolean;
  deliveryDate?: boolean;
  deliveryAddress?: boolean;
  deliveryTimeWindow?: boolean;
  npOfficeNumber?: boolean;
  npCityRef?: boolean;
  npWarehouseRef?: boolean;
  pickupTime?: boolean;
  cardMessage?: boolean;
  paymentMethod?: boolean;
  comment?: boolean;
  items?:
    | boolean
    | {
        product?: boolean;
        productName?: boolean;
        variantLabel?: boolean;
        quantity?: boolean;
        unitPrice?: boolean;
        lineTotal?: boolean;
        id?: boolean;
      };
  orderTotal?: boolean;
  status?: boolean;
  paymentStatus?: boolean;
  paymentProvider?: boolean;
  paymentReference?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-inquiries_select".
 */
export interface WeddingInquiriesSelect {
  customerName?: boolean;
  phone?: boolean;
  email?: boolean;
  weddingDate?: boolean;
  guestsCount?: boolean;
  budget?: boolean;
  comment?: boolean;
  status?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-bouquet-requests_select".
 */
export interface CustomBouquetRequestsSelect {
  customerName?: boolean;
  phone?: boolean;
  gamma?: boolean;
  budget?: boolean;
  occasion?: boolean;
  likedFlowers?: boolean;
  dislikedFlowers?: boolean;
  cardMessage?: boolean;
  referencePhoto?: boolean;
  status?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-inquiries_select".
 */
export interface BusinessInquiriesSelect {
  companyName?: boolean;
  contactPerson?: boolean;
  phone?: boolean;
  businessType?: boolean;
  budgetOrLocations?: boolean;
  status?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect {
  key?: boolean;
  data?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect {
  document?: boolean;
  globalSlug?: boolean;
  user?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect {
  user?: boolean;
  key?: boolean;
  value?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect {
  name?: boolean;
  batch?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  heading: string;
  subheading?: string | null;
  video?: (number | null) | Media;
  /**
   * Постер відео та резервне зображення для мобільних
   */
  fallbackImage: number | Media;
  ctaButtons?:
    | {
        label: string;
        href: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Перемикає весь сайт між старою та новою фірмовою темою
   */
  designTheme?: ('old' | 'new') | null;
  /**
   * Лого в шапці сайту (замінює текстовий напис "kvitkova povnya")
   */
  logo?: (number | null) | Media;
  contactPhone?: string | null;
  contactEmail?: string | null;
  instagramUrl?: string | null;
  /**
   * Посилання на Telegram (канал або чат для звʼязку) — використовується у футері
   */
  telegramUrl?: string | null;
  /**
   * Адреса шоуруму/студії для самовивозу — показується на сторінці чекауту
   */
  showroomAddress?: string | null;
  /**
   * Посилання Google Maps на шоурум — адреса у футері та на сторінці контактів веде сюди
   */
  googleMapsUrl?: string | null;
  deliveryCities?:
    | {
        name: string;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-info".
 */
export interface SubscriptionInfo {
  id: number;
  tickerText?: string | null;
  heading: string;
  intro: string;
  image?: (number | null) | Media;
  frequenciesHeading?: string | null;
  frequencies?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  minimumHeading?: string | null;
  minimumIncludes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  eachDeliveryHeading?: string | null;
  eachDeliveryIncludes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-page".
 */
export interface WeddingPage {
  id: number;
  heading: string;
  subheading?: string | null;
  ctaLabel?: string | null;
  intro: string;
  /**
   * Блок "Як це працює"
   */
  steps?:
    | {
        icon: 'truck' | 'vase' | 'pause' | 'flower' | 'home' | 'sparkle';
        title: string;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  formHeading?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Фото ваших весільних робіт — портфоліо
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  contactNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Блок із 4 картками під головним банером (дім, букети, бізнес, весілля)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formats-section".
 */
export interface FormatsSection {
  id: number;
  heading?: string | null;
  cards?:
    | {
        title: string;
        subtitle: string;
        buttonLabel: string;
        buttonHref: string;
        image?: (number | null) | Media;
        /**
         * Визначає порядок карток зліва направо (менше число — раніше)
         */
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Налаштування підключення до Instagram Graph API та ручний список дописів. Поки accessToken не заповнений, на сайті показується ручний список нижче.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-integration".
 */
export interface InstagramIntegration {
  id: number;
  /**
   * Довгостроковий Page Access Token з дозволами instagram_basic, pages_show_list, pages_read_engagement (Meta Graph API Explorer → Access Token Debugger → Extend Access Token).
   */
  accessToken?: string | null;
  /**
   * Instagram Business Account ID. Отримується через GET /me/accounts, поле instagram_business_account для потрібної сторінки.
   */
  igUserId?: string | null;
  /**
   * Скільки останніх дописів підтягувати для стрічки на головній сторінці
   */
  postLimit?: number | null;
  /**
   * Показується на сайті, поки не заповнені accessToken та igUserId вище (автопідключення до Graph API)
   */
  instagramPosts?:
    | {
        image: number | Media;
        /**
         * Посилання на пост (необовʼязково)
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Ряд із 3 переваг з іконками під головним банером (лише в новому дизайні)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-strip".
 */
export interface FeatureStrip {
  id: number;
  heading?: string | null;
  items?:
    | {
        icon: 'truck' | 'vase' | 'pause' | 'flower' | 'home' | 'sparkle';
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Заголовок і пронумеровані кроки (лише в новому дизайні)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works-section".
 */
export interface HowItWorksSection {
  id: number;
  heading: string;
  steps?:
    | {
        icon: 'truck' | 'vase' | 'pause' | 'flower' | 'home' | 'sparkle';
        title: string;
        subtitle?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Фотогалереї для розмірів у калькуляторі підписки на головній. Ціна, назва розміру (S/M/L/XXL) та бейдж "Хіт" беруться напряму з варіантів товару "Підписка на квіти" (розділ Каталог → Товари, позначений як "Виділений") — тут редагується лише поле label (для збігу з назвою варіанту) і фото.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-pricing".
 */
export interface SubscriptionPricing {
  id: number;
  sizes?:
    | {
        /**
         * Має точно збігатися з назвою варіанту (S/M/L/XXL) у товарі "Підписка на квіти"
         */
        label: string;
        /**
         * Фото букета саме цього розміру для галереї в калькуляторі. Якщо порожньо — показуються загальні фото товару підписки.
         */
        images?:
          | {
              image: number | Media;
              alt?: string | null;
              /**
               * Порядок показу — менше число показується раніше
               */
              sortOrder?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Скріншоти відгуків та рейтинг, що показуються в каруселі "Відгуки" на головній сторінці
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Рейтинг для плашки "★ 5.0 на основі відгуків у Google" над каруселлю
   */
  googleRating?: string | null;
  /**
   * Текст поруч з рейтингом Google над каруселлю
   */
  happySubscribersStat?: string | null;
  /**
   * Скріншоти відгуків клієнтів (напр. з Instagram Stories/Highlights — завантаж скріншот сюди, Instagram не дає підтягувати їх автоматично)
   */
  testimonials?:
    | {
        image: number | Media;
        /**
         * Ім'я клієнта (необовʼязково)
         */
        authorName?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Питання-відповіді в акордеоні "Часті запитання" внизу головної сторінки
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section".
 */
export interface FaqSection {
  id: number;
  faqItems?:
    | {
        question: string;
        answer: string;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect {
  heading?: boolean;
  subheading?: boolean;
  video?: boolean;
  fallbackImage?: boolean;
  ctaButtons?:
    | boolean
    | {
        label?: boolean;
        href?: boolean;
        style?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect {
  designTheme?: boolean;
  logo?: boolean;
  contactPhone?: boolean;
  contactEmail?: boolean;
  instagramUrl?: boolean;
  telegramUrl?: boolean;
  showroomAddress?: boolean;
  googleMapsUrl?: boolean;
  deliveryCities?:
    | boolean
    | {
        name?: boolean;
        active?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-info_select".
 */
export interface SubscriptionInfoSelect {
  tickerText?: boolean;
  heading?: boolean;
  intro?: boolean;
  image?: boolean;
  frequenciesHeading?: boolean;
  frequencies?:
    | boolean
    | {
        label?: boolean;
        id?: boolean;
      };
  minimumHeading?: boolean;
  minimumIncludes?:
    | boolean
    | {
        label?: boolean;
        id?: boolean;
      };
  eachDeliveryHeading?: boolean;
  eachDeliveryIncludes?:
    | boolean
    | {
        label?: boolean;
        id?: boolean;
      };
  ctaLabel?: boolean;
  ctaHref?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-page_select".
 */
export interface WeddingPageSelect {
  heading?: boolean;
  subheading?: boolean;
  ctaLabel?: boolean;
  intro?: boolean;
  steps?:
    | boolean
    | {
        icon?: boolean;
        title?: boolean;
        subtitle?: boolean;
        id?: boolean;
      };
  formHeading?: boolean;
  coverImage?: boolean;
  gallery?:
    | boolean
    | {
        image?: boolean;
        caption?: boolean;
        id?: boolean;
      };
  contactNote?: boolean;
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formats-section_select".
 */
export interface FormatsSectionSelect {
  heading?: boolean;
  cards?:
    | boolean
    | {
        title?: boolean;
        subtitle?: boolean;
        buttonLabel?: boolean;
        buttonHref?: boolean;
        image?: boolean;
        sortOrder?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-integration_select".
 */
export interface InstagramIntegrationSelect {
  accessToken?: boolean;
  igUserId?: boolean;
  postLimit?: boolean;
  instagramPosts?:
    | boolean
    | {
        image?: boolean;
        link?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-strip_select".
 */
export interface FeatureStripSelect {
  heading?: boolean;
  items?:
    | boolean
    | {
        icon?: boolean;
        title?: boolean;
        description?: boolean;
        id?: boolean;
      };
  cta?:
    | boolean
    | {
        label?: boolean;
        href?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "how-it-works-section_select".
 */
export interface HowItWorksSectionSelect {
  heading?: boolean;
  steps?:
    | boolean
    | {
        icon?: boolean;
        title?: boolean;
        subtitle?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-pricing_select".
 */
export interface SubscriptionPricingSelect {
  sizes?:
    | boolean
    | {
        label?: boolean;
        images?:
          | boolean
          | {
              image?: boolean;
              alt?: boolean;
              sortOrder?: boolean;
              id?: boolean;
            };
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect {
  googleRating?: boolean;
  happySubscribersStat?: boolean;
  testimonials?:
    | boolean
    | {
        image?: boolean;
        authorName?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-section_select".
 */
export interface FaqSectionSelect {
  faqItems?:
    | boolean
    | {
        question?: boolean;
        answer?: boolean;
        sortOrder?: boolean;
        id?: boolean;
      };
  updatedAt?: boolean;
  createdAt?: boolean;
  globalType?: boolean;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}