/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    orders: Order;
    'wedding-inquiries': WeddingInquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'wedding-inquiries': WeddingInquiriesSelect<false> | WeddingInquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    'site-settings': SiteSetting;
    'subscription-info': SubscriptionInfo;
    'wedding-page': WeddingPage;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'subscription-info': SubscriptionInfoSelect<false> | SubscriptionInfoSelect<true>;
    'wedding-page': WeddingPageSelect<false> | WeddingPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'owner' | 'florist';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  /**
   * Той самий товар може належати кільком категоріям (напр. підписка одночасно й "Підписка на квіти", й "Весільна підписка")
   */
  categories: (number | Category)[];
  /**
   * Базова ціна в копійках (щоб уникнути похибок округлення), напр. 45000 = 450.00 грн
   */
  price: number;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Напр. розмір букета або частота підписки
   */
  variants?:
    | {
        label: string;
        /**
         * Копійки, може бути відʼємним
         */
        priceModifier?: number | null;
        /**
         * Якщо вказано, замінює фото товару при виборі цього варіанту
         */
        image?: (number | null) | Media;
        sku?: string | null;
        id?: string | null;
      }[]
    | null;
  inStock?: boolean | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  customerName: string;
  phone: string;
  email?: string | null;
  deliveryCity: string;
  deliveryDate: string;
  deliveryAddress: string;
  deliveryTimeWindow: '09:00-12:00' | '12:00-15:00' | '15:00-18:00' | '18:00-21:00';
  /**
   * Текст листівки
   */
  cardMessage?: string | null;
  comment?: string | null;
  items: {
    product: number | Product;
    productName: string;
    variantLabel?: string | null;
    quantity: number;
    /**
     * Копійки
     */
    unitPrice: number;
    /**
     * Копійки
     */
    lineTotal: number;
    id?: string | null;
  }[];
  /**
   * Копійки, рахується автоматично
   */
  orderTotal?: number | null;
  status: 'new' | 'confirmed' | 'in_progress' | 'done' | 'cancelled';
  paymentStatus?: ('not_required' | 'pending' | 'paid' | 'failed' | 'refunded') | null;
  paymentProvider?: ('none' | 'monobank_acquiring' | 'monobank_installments') | null;
  paymentReference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-inquiries".
 */
export interface WeddingInquiry {
  id: number;
  customerName: string;
  phone: string;
  email?: string | null;
  weddingDate?: string | null;
  guestsCount?: number | null;
  /**
   * Орієнтовний бюджет, напр. '20000-30000 грн'
   */
  budget?: string | null;
  comment?: string | null;
  status: 'new' | 'contacted' | 'consultation_scheduled' | 'won' | 'lost';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'wedding-inquiries';
        value: number | WeddingInquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  categories?: T;
  price?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        label?: T;
        priceModifier?: T;
        image?: T;
        sku?: T;
        id?: T;
      };
  inStock?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customerName?: T;
  phone?: T;
  email?: T;
  deliveryCity?: T;
  deliveryDate?: T;
  deliveryAddress?: T;
  deliveryTimeWindow?: T;
  cardMessage?: T;
  comment?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        variantLabel?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  orderTotal?: T;
  status?: T;
  paymentStatus?: T;
  paymentProvider?: T;
  paymentReference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-inquiries_select".
 */
export interface WeddingInquiriesSelect<T extends boolean = true> {
  customerName?: T;
  phone?: T;
  email?: T;
  weddingDate?: T;
  guestsCount?: T;
  budget?: T;
  comment?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  heading: string;
  subheading?: string | null;
  video?: (number | null) | Media;
  /**
   * Постер відео та резервне зображення для мобільних
   */
  fallbackImage: number | Media;
  ctaButtons?:
    | {
        label: string;
        href: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Лого в шапці сайту (замінює текстовий напис "kvitkova povnya")
   */
  logo?: (number | null) | Media;
  contactPhone?: string | null;
  contactEmail?: string | null;
  instagramUrl?: string | null;
  /**
   * Фото з Instagram для стрічки на головній сторінці
   */
  instagramPosts?:
    | {
        image: number | Media;
        /**
         * Посилання на пост (необовʼязково)
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Скріншоти відгуків клієнтів (напр. з Instagram Stories/Highlights — завантаж скріншот сюди, Instagram не дає підтягувати їх автоматично)
   */
  testimonials?:
    | {
        image: number | Media;
        /**
         * Ім'я клієнта (необовʼязково)
         */
        authorName?: string | null;
        id?: string | null;
      }[]
    | null;
  deliveryCities?:
    | {
        name: string;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-info".
 */
export interface SubscriptionInfo {
  id: number;
  tickerText?: string | null;
  heading: string;
  intro: string;
  image?: (number | null) | Media;
  frequenciesHeading?: string | null;
  frequencies?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  minimumHeading?: string | null;
  minimumIncludes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  eachDeliveryHeading?: string | null;
  eachDeliveryIncludes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-page".
 */
export interface WeddingPage {
  id: number;
  heading: string;
  intro: string;
  coverImage?: (number | null) | Media;
  /**
   * Фото ваших весільних робіт — портфоліо
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  contactNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  video?: T;
  fallbackImage?: T;
  ctaButtons?:
    | T
    | {
        label?: T;
        href?: T;
        style?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  contactPhone?: T;
  contactEmail?: T;
  instagramUrl?: T;
  instagramPosts?:
    | T
    | {
        image?: T;
        link?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        image?: T;
        authorName?: T;
        id?: T;
      };
  deliveryCities?:
    | T
    | {
        name?: T;
        active?: T;
        id?: T;
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        sortOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription-info_select".
 */
export interface SubscriptionInfoSelect<T extends boolean = true> {
  tickerText?: T;
  heading?: T;
  intro?: T;
  image?: T;
  frequenciesHeading?: T;
  frequencies?:
    | T
    | {
        label?: T;
        id?: T;
      };
  minimumHeading?: T;
  minimumIncludes?:
    | T
    | {
        label?: T;
        id?: T;
      };
  eachDeliveryHeading?: T;
  eachDeliveryIncludes?:
    | T
    | {
        label?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-page_select".
 */
export interface WeddingPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  contactNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}